use phf::phf_map;

pub const TOOLS: phf::Map<&'static str, &'static [&'static str]> = phf_map! {
    // languages
    "python" => &["python", "--version"],
    "python3" => &["python3", "--version"],
    "node" => &["node", "--version"],
    "ruby" => &["ruby", "--version"],
    "go" => &["go", "version"],
    "java" => &["java", "--version"],
    "rustc" => &["rustc", "--version"],
    "gcc" => &["gcc", "--version"],
    "clang" => &["clang", "--version"],
    "deno" => &["deno", "--version"],
    "elixir" => &["elixir", "--version"],
    "erlang" => &["erl", "-eval", "erlang:display(erlang:system_info(otp_release)), halt().", "-noshell"],
    "kotlin" => &["kotlin", "-version"],
    "scala" => &["scala", "-version"],
    "swift" => &["swift", "--version"],
    "php" => &["php", "--version"],
    "perl" => &["perl", "--version"],
    "lua" => &["lua", "-v"],
    "dotnet" => &["dotnet", "--version"],
    "zig" => &["zig", "version"],
    // package managers
    "pip" => &["pip", "--version"],
    "pip3" => &["pip3", "--version"],
    "cargo" => &["cargo", "--version"],
    "npm" => &["npm", "--version"],
    "yarn" => &["yarn", "--version"],
    "pnpm" => &["pnpm", "--version"],
    "bun" => &["bun", "--version"],
    "gem" => &["gem", "--version"],
    "composer" => &["composer", "--version"],
    "maven" => &["mvn", "--version"],
    "gradle" => &["gradle", "--version"],
    "mix" => &["mix", "--version"],
    "poetry" => &["poetry", "--version"],
    "pipenv" => &["pipenv", "--version"],
    "uv" => &["uv", "--version"],
    // tools
    "git" => &["git", "--version"],
    "docker" => &["docker", "--version"],
    "kubectl" => &["kubectl", "version", "--client"],
    "terraform" => &["terraform", "--version"],
    "make" => &["make", "--version"],
    "cmake" => &["cmake", "--version"],
    "curl" => &["curl", "--version"],
    "wget" => &["wget", "--version"],
    "helm" => &["helm", "version"],
    "ansible" => &["ansible", "--version"],
    "vault" => &["vault", "--version"],
    "redis-cli" => &["redis-cli", "--version"],
    "psql" => &["psql", "--version"],
    "mysql" => &["mysql", "--version"],
    "sqlite3" => &["sqlite3", "--version"],
    "ffmpeg" => &["ffmpeg", "-version"],
    "jq" => &["jq", "--version"],
};

pub const FIX_COMMANDS: phf::Map<&'static str, &'static str> = phf_map! {
    // languages
    "python" => "https://www.python.org/downloads/",
    "python3" => "https://www.python.org/downloads/",
    "node" => "https://nodejs.org/en/download",
    "ruby" => "https://www.ruby-lang.org/en/documentation/installation/",
    "go" => "https://go.dev/dl/",
    "java" => "https://adoptium.net/",
    "rustc" => "https://rustup.rs/",
    "gcc" => "https://gcc.gnu.org/install/",
    "clang" => "https://releases.llvm.org/",
    "deno" => "https://deno.land/#installation",
    "elixir" => "https://elixir-lang.org/install.html",
    "erlang" => "https://www.erlang.org/downloads",
    "kotlin" => "https://kotlinlang.org/docs/command-line.html",
    "scala" => "https://www.scala-lang.org/download/",
    "swift" => "https://www.swift.org/download/",
    "php" => "https://www.php.net/downloads",
    "perl" => "https://www.perl.org/get.html",
    "lua" => "https://www.lua.org/download.html",
    "dotnet" => "https://dotnet.microsoft.com/download",
    "zig" => "https://ziglang.org/download/",
    // package managers
    "pip" => "python -m ensurepip --upgrade",
    "pip3" => "python3 -m ensurepip --upgrade",
    "cargo" => "https://rustup.rs/",
    "npm" => "https://nodejs.org/en/download",
    "yarn" => "npm install -g yarn",
    "pnpm" => "npm install -g pnpm",
    "bun" => "https://bun.sh/",
    "gem" => "https://www.ruby-lang.org/en/documentation/installation/",
    "composer" => "https://getcomposer.org/download/",
    "maven" => "https://maven.apache.org/download.cgi",
    "gradle" => "https://gradle.org/install/",
    "mix" => "https://elixir-lang.org/install.html",
    "poetry" => "pip install poetry",
    "pipenv" => "pip install pipenv",
    "uv" => "pip install uv",
    // tools
    "git" => "https://git-scm.com/downloads",
    "docker" => "https://docs.docker.com/get-docker/",
    "kubectl" => "https://kubernetes.io/docs/tasks/tools/",
    "terraform" => "https://developer.hashicorp.com/terraform/install",
    "make" => "https://www.gnu.org/software/make/",
    "cmake" => "https://cmake.org/download/",
    "curl" => "https://curl.se/download.html",
    "wget" => "https://www.gnu.org/software/wget/",
    "helm" => "https://helm.sh/docs/intro/install/",
    "ansible" => "pip install ansible",
    "vault" => "https://developer.hashicorp.com/vault/install",
    "redis-cli" => "https://redis.io/docs/getting-started/",
    "psql" => "https://www.postgresql.org/download/",
    "mysql" => "https://dev.mysql.com/downloads/",
    "sqlite3" => "https://www.sqlite.org/download.html",
    "ffmpeg" => "https://ffmpeg.org/download.html",
    "jq" => "https://jqlang.github.io/jq/download/",
};